style:
  # handled by ktlint
  MaxLineLength:
    active: false
  ModifierOrder:
    active: false

  # No need for this
  ReturnCount:
    active: false
  ThrowsCount:
    active: false

# Enforce some proper documentation standards (cf. MODELIX-794)
comments:
  OutdatedDocumentation:
    active: true
  UndocumentedPublicClass:
    active: true
  UndocumentedPublicFunction:
    active: true
  UndocumentedPublicProperty:
    active: true
