extends:
  - https://raw.githubusercontent.com/baloise-incubator/spectral-ruleset/5b2386ffa4d0ab4ccef0e1fc87f3d00fefc81eea/zalando.yml
  - "spectral:oas"
rules:
  # We don't need an API info for internal use
  must-have-info-contact-email: false
  must-have-info-contact-name: false
  must-have-info-contact-url: false
  must-have-info-x-api-id: false
  must-provide-api-audience: false

  # The rule is based on an outdated problem specification
  must-use-valid-problem-json-schema: false

  # We would lose enum support from openapi-generator
  should-use-x-extensible-enum: false
