services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8080
      KC_HOSTNAME: localhost
    volumes:
      - ./realm.json:/opt/keycloak/data/import/realm.json
    ports:
      - "28180:8080"
    networks:
      - app-network

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    environment:
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_OIDC_ISSUER_URL: http://keycloak:8080/realms/modelix
      OAUTH2_PROXY_SKIP_OIDC_DISCOVERY: "true"
      OAUTH2_PROXY_LOGIN_URL: http://localhost:28180/realms/modelix/protocol/openid-connect/auth
      OAUTH2_PROXY_REDEEM_URL: http://keycloak:8080/realms/modelix/protocol/openid-connect/token
      OAUTH2_PROXY_OIDC_JWKS_URL: http://keycloak:8080/realms/modelix/protocol/openid-connect/certs
      OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL: "true"
      OAUTH2_PROXY_INSECURE_OIDC_SKIP_ISSUER_VERIFICATION: "true"
      OAUTH2_PROXY_CLIENT_ID: oauth2-proxy
      OAUTH2_PROXY_CLIENT_SECRET: 8g!.4RpL2tPxdXMMK6mb
      OAUTH2_PROXY_COOKIE_SECRET: jLTKkbMwRJpsS7ZW
      OAUTH2_PROXY_UPSTREAMS: http://model-server:28101/
      OAUTH2_PROXY_REDIRECT_URL: http://localhost:4180/oauth2/callback
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_COOKIE_HTTPONLY: "false"
      OAUTH2_PROXY_COOKIE_SECURE: "false"
      OAUTH2_PROXY_SET_AUTHORIZATION_HEADER: "true"
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: "true"
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
      OAUTH2_PROXY_SCOPE: "sync openid"
    ports:
      - "4180:4180"
    depends_on:
      - keycloak
    networks:
      - app-network

  model-server:
    build:
      context: ../model-server
      dockerfile: Dockerfile
    command: ["--inmemory"]
    environment:
      MODELIX_AUTHORIZATION_URI: http://localhost:28180/realms/modelix/protocol/openid-connect/auth
      MODELIX_TOKEN_URI: http://localhost:28180/realms/modelix/protocol/openid-connect/token
      MODELIX_PERMISSION_CHECKS_ENABLED: true
      MODELIX_JWK_URI_KEYCLOAK: http://keycloak:8080/realms/modelix/protocol/openid-connect/certs
    ports:
      - "28101:28101"
    networks:
      - app-network
    depends_on:
      - keycloak

networks:
  app-network:
    driver: bridge
