name: Build

on:
  push:
    branches:
      - 'main'
  pull_request: {}
  # allow manual execution just in case
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build
        uses: gradle/gradle-build-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: |
            --build-cache
            build
            -PciBuild=true
      - name: Archive test report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-report
          path: |
            */build/test-results
            */build/reports

  test-model-api-gen-gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Assemble
        uses: gradle/gradle-build-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: |
            --build-cache
            assemble
            publishToMavenLocal
            -PciBuild=true
      - name: Test Model API Generator Gradle Plugin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: model-api-gen-gradle-test/ci.sh

  test-bulk-model-sync-gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Assemble
        uses: gradle/gradle-build-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: |
            --build-cache
            assemble
            publishToMavenLocal
            -PciBuild=true

      - name: Test Bulk Model Sync Gradle Plugin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bulk-model-sync-gradle-test/ci.sh
