name: MPS compatibility

on:
  push:
    branches:
      - 'main'
  pull_request: {}
  # allow manual execution just in case
  workflow_dispatch:

jobs:
  build-mps-components:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with MPS 2020.3.6
        run: ./gradlew :mps-model-adapters:build :mps-model-server-plugin:build -Pmps.version=2020.3.6
      - name: Build with MPS 2021.1.4
        run: ./gradlew :mps-model-adapters:build :mps-model-server-plugin:build -Pmps.version=2021.1.4
      - name: Build with MPS 2021.2.6
        run: ./gradlew :mps-model-adapters:build :mps-model-server-plugin:build -Pmps.version=2021.2.6
      - name: Build with MPS 2021.3.3
        run: ./gradlew :mps-model-adapters:build :mps-model-server-plugin:build -Pmps.version=2021.3.3
      - name: Build with MPS 2022.2
        run: ./gradlew :mps-model-adapters:build :mps-model-server-plugin:build -Pmps.version=2022.2
      - name: Build with MPS 2022.3
        run: ./gradlew :mps-model-adapters:build :mps-model-server-plugin:build -Pmps.version=2022.3
